# Generated by Django 5.2.1 on 2025-05-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_customer_first_name_alter_customer_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='slug',
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(error_messages='Oopsie', help_text='max 30 letters', max_length=30),
        ),
    ]
